#!/usr/bin/env python3
"""Build the weekly-report-dashboard landing page."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

BASE = Path('/home/cheta/code/weekly-report-dashboard')


def bundles():
    rows = []
    for p in sorted(BASE.glob('*'), reverse=True):
        if p.is_dir() and (p / 'index.html').exists() and p.name != 'daily':
            rows.append(('Weekly', p.name, f'./{p.name}/'))
    daily = BASE / 'daily'
    if daily.exists():
        for p in sorted(daily.glob('*'), reverse=True):
            if p.is_dir() and (p / 'index.html').exists():
                rows.append(('Daily', p.name, f'./daily/{p.name}/'))
    return rows


def main():
    BASE.mkdir(parents=True, exist_ok=True)
    rows = bundles()
    cards = '\n'.join(
        f'<a class="card" href="{href}"><span>{kind}</span><strong>{date}</strong><small>{href}</small></a>'
        for kind, date, href in rows
    ) or '<p class="muted">No report bundles found.</p>'
    html = f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Report Dashboard Index</title>
  <style>
    body {{ margin:0; background:#08090a; color:#f7f8f8; font-family:Inter,system-ui,sans-serif; }}
    main {{ width:min(980px,calc(100% - 40px)); margin:0 auto; padding:48px 0; }}
    h1 {{ font-size:48px; letter-spacing:-1px; margin:0 0 10px; font-weight:560; }}
    p {{ color:#8a8f98; line-height:1.6; }}
    .grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(240px,1fr)); gap:14px; margin-top:28px; }}
    .card {{ display:flex; flex-direction:column; gap:8px; padding:18px; border:1px solid rgba(255,255,255,.08); border-radius:16px; background:rgba(255,255,255,.04); color:inherit; text-decoration:none; }}
    .card:hover {{ background:rgba(113,112,255,.12); }}
    span, small {{ color:#8a8f98; }}
    strong {{ font-size:24px; }}
    .muted {{ color:#8a8f98; }}
  </style>
</head>
<body>
  <main>
    <h1>Report Dashboard Index</h1>
    <p>Daily and weekly report bundles generated by weekly-report-suite. Updated {datetime.now(timezone.utc).isoformat()}.</p>
    <div class="grid">{cards}</div>
  </main>
</body>
</html>
'''
    (BASE / 'index.html').write_text(html)
    print(BASE / 'index.html')


if __name__ == '__main__':
    main()
